### ISSUE TITLE
 Plugin not compatible with last version of sonar-scanner

### ISSUE THREAD

**Issue by diegorodriguez31** [Linty-Services/sonar-modelsim-plugin#17]
Good Morning,

The plugin is not compatible with the latest version of SonarQube (LTS 9.9).

I have the following error when I try to run a Sonar-Scanner analysis (either SC version 4.8 or 4.4).

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.sonarsource.scanner.api.internal.IsolatedClassloader@689604d9-org.sonar.scanner.bootstrap.ScannerPluginRepository': Initialization of bean failed; nested exception is java.lang.IllegalStateException: The plugin [modelsim] does not support Java 11.0.19`

Do you know when this pluggin will be updated ?

Thank you.

**Comment by racodond** [comment]
Hi @diegorodriguez31,

I just released version 1.10.0 that is compatible with both SonarQube 9.9 (LTS) and 10.0 (latest): https://github.com/Linty-Services/sonar-modelsim-plugin/releases/tag/1.10.0
All Linty plugins require Java 17 to run.

Regards,

David

**Comment by diegorodriguez31** [comment]
Thank you very much for your prompt update @racodond.

Regards,
Diego

**Comment by diegorodriguez31** [comment]
@racodond 
Can you use the latest version of sonar-scanner when you embed the plugin in SonarQube ? I still have the error.

Sonar-scanner is not compatible with Java 17. When I run an analysis on a project, the plugin triggers the same error as my first comment.

**Comment by racodond** [comment]
The plugin is compatible with the latest version of the Sonar Scanner. Sonar Scanner is compatible with both Java 11 and 17. See https://docs.sonarqube.org/latest/requirements/prerequisites-and-overview/#supported-platforms. But all our Linty plugins now require Java 17. Thus, you have to install Java 17 on the machine running the Sonar Scanner.

**Comment by diegorodriguez31** [comment]
> The plugin is compatible with the latest version of the Sonar Scanner. Sonar Scanner is compatible with both Java 11 and 17. See https://docs.sonarqube.org/latest/requirements/prerequisites-and-overview/#supported-platforms. But all our Linty plugins now require Java 17. Thus, you have to install Java 17 on the machine running the Sonar Scanner.

Thank you.
Before posting my previous comment, I tried to run the analysis on a openjdk:17-jdk-slim image and with the latest version of sonar-scanner. Maybe the slim image is not compatible... I will investigate and let you know if I resolve this problem.

**Comment by racodond** [comment]
@diegorodriguez31 : Any feedback on this issue? Thanks
